// <auto-generated />
namespace MVCLectures.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GenreNameRequired255Characters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreNameRequired255Characters));
        
        string IMigrationMetadata.Id
        {
            get { return "201712272234536_GenreNameRequired255Characters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
